name: Testing Features
run-name: ${{ github.actor }} is testing feature metrics 🚀
on: [push]
jobs:
  Testing-Features:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./feature_engine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd testing
          pytest test_feature_metrics.py

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: test-log
          path: testing/test.log
        if: ${{ always() }}

      # - name: Upload pytest test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: pytest-results
      #     path: testing
      #   # Use always() to always run this step to publish test results when there are test failures
      #
